### PR TITLE
Renames to hypertrace-service and docker image to hypertrace

### LINKED ISSUE #18: Rename this repository, references and binaries to "hypertrace-service", docker to "hypertrace"
Due to a lot of work led (and often implemented) by @kotharironak, all functionality supporting the frontend UI are now consolidated here. This service is only for Hypertrace, in other words. It is now the canonical entrypoint into Hypertrace, even if stream ingestion services are required for getting data into the system.  Hence, the name "hypertrace-service" is a more intuitive name and should be used everywhere, except the docker image, as "hypertrace" is a better name for that imho.

Changing this requires at least the following:
* setup of 'hypertrace/hypertrace' in DockerHub, so later publishing can work
* changes to configuration in this repository, corresponding CI setup that calls the java side "hypertrace-service" but publishes the "hypertrace" image
* Next month, delete the old docker images, as they were <1.0 anyway and will cause confusion

# Why not keep federated?

Federated hints often at identity concerns which are not present in this repo. We want people to notice this repository, instead of dismiss it as something else.

# Why "hypertrace" in docker instead of "hypertrace-service"

It isn't common to suffix the primary entrypoint of services, and it makes search easier if you don't. The most intuitive name for the frontend is "hypertrace". Ack that the ingestion parts are not currently present, but that doesn't mean in the future they can't be. Using an intuitive name can help us also from having to rename later again.

### PR DESCRIPTION
**Pull request by adriancole**
This also updates to latest build plugins

Fixes #18

### CODE REVIEW

**Comment by adriancole** [comment]
https://github.com/hypertrace/hypertrace/pull/49 uses this when published

**Review by kotharironak — COMMENTED** [review]
lgtm

**Review by kotharironak — APPROVED** [review]

**Comment by kotharironak** [comment]
@ravisingal Can you check this out once too?
cc: @adriancole

**Comment by adriancole** [comment]
As this is only going to update :main and also only effects OSS, I'm going to merge rather than push another day. Feedback welcome post merge and I'll chase up whatever that is.

**Pull request merged**
